# Generated by Django 5.2 on 2025-06-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_annotation_dataitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.TextField(blank=True),
        ),
    ]
